### ISSUE TITLE
Crash during world generation

### ISSUE THREAD

**Issue by Zarepheth** [gegy1000/JurassiCraft2#93] opened 2016-09-11 03:15 UTC
I've been playing a map with numerous installed mods. Everything was going fine, until I got to a point where traveling towards a particular region of the map would cause a crash-to-desktop.

I've attached two crash reports. Both have a stack trace whose most recent mod, prior to the exception, is JurassiCraft.

[crash-2016-09-10_20.22.31-server.txt](https://github.com/gegy1000/JurassiCraft2/files/465742/crash-2016-09-10_20.22.31-server.txt)
[crash-2016-09-10_20.20.13-server.txt](https://github.com/gegy1000/JurassiCraft2/files/465743/crash-2016-09-10_20.20.13-server.txt)

**Comment by gegy1000** [comment] 2016-09-11 07:25
Duplicate of #90 and will be fixed in the next release. For now disable petrified tree generation.

**Closed by gegy1000** 2016-09-11 07:25 UTC
