### ISSUE TITLE
1.10.2 World Generation Crash

### ISSUE THREAD

**Issue by MokahTGS** [gegy1000/JurassiCraft2#90] opened 2016-08-28 02:25 UTC
Getting a crash exploring the world with Forge 2072 and JC v2.0.2

http://pastebin.com/vq7NxLUs

**Comment by gegy1000** [comment] 2016-08-28 08:10
Duplicate of #82, as said on that issue, disable petrified tree generation until the next update.

**Closed by gegy1000** 2016-08-28 08:10 UTC
Labels: bug, crash
