### ISSUE TITLE
Dino's cause high TPS/Tick rate

### ISSUE THREAD

**Issue by darkphan** [gegy1000/JurassiCraft2#105] opened 2016-11-04 00:29 UTC
In Minecraft 1.10.2, Forge 12.18.2.2116 dinos in the world cause high tick rate. Picking them up in a golden lasso will cause the tick rate to immediately go to normal

**Comment by gegy1000** [comment] 2016-11-04 05:42
Duplicate of #101

**Closed by gegy1000** 2016-11-04 05:42 UTC
